/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alterarSenha` | `/alterarSenha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/setups` | `/setups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/upgrade` | `/upgrade`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(auth)'}/logout` | `/logout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/investments` | `/investments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reports` | `/reports`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/alterarSenha` | `/alterarSenha`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/setups` | `/setups`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/upgrade` | `/upgrade`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(auth)'}/logout` | `/logout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/investments` | `/investments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reports` | `/reports`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/alterarSenha${`?${string}` | `#${string}` | ''}` | `/alterarSenha${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/setups${`?${string}` | `#${string}` | ''}` | `/setups${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/upgrade${`?${string}` | `#${string}` | ''}` | `/upgrade${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(auth)'}/logout${`?${string}` | `#${string}` | ''}` | `/logout${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/investments${`?${string}` | `#${string}` | ''}` | `/investments${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/reports${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alterarSenha` | `/alterarSenha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/setups` | `/setups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/upgrade` | `/upgrade`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(auth)'}/logout` | `/logout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/investments` | `/investments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reports` | `/reports`; params?: Router.UnknownInputParams; };
    }
  }
}
